-- Oracle Database Schema for DocuDigitize Pro
-- REFACTORED: IDs are now VARCHAR2(50) with 'p-' prefix auto-generated via Triggers.
-- REMOVED: DOC_REFS table and REF_ID column.

-- Drop tables/sequences to reset (Clean Slate)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PATIENT_DOC_INFO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE PATIENT_INFO CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE DOCTOR_INFO CASCADE CONSTRAINTS';
  -- EXECUTE IMMEDIATE 'DROP TABLE DOC_REFS CASCADE CONSTRAINTS'; -- Removed
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PATIENT_ID';
  EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DR_ID';
  -- EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REF_ID'; -- Removed
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 AND SQLCODE != -2289 THEN RAISE; END IF;
END;
/

-- 1b. Doctor Info Table
CREATE TABLE DOCTOR_INFO (
  DR_ID VARCHAR2(50) NOT NULL, -- Changed to VARCHAR2
  DR_NAME VARCHAR2(200),
  ADDRESS VARCHAR2(200),
  REG_NO VARCHAR2(50),
  CONTACT_NO NUMBER,
  EMAIL VARCHAR2(30),
  REMARKS VARCHAR2(200),
  PRIMARY KEY (DR_ID)
);

CREATE SEQUENCE SEQ_DR_ID START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_DR_ID
BEFORE INSERT ON DOCTOR_INFO
FOR EACH ROW
BEGIN
  IF :NEW.DR_ID IS NULL THEN
    :NEW.DR_ID := 'p-' || SEQ_DR_ID.NEXTVAL;
  END IF;
END;
/

-- Seed Data for Doctors
INSERT INTO DOCTOR_INFO (DR_NAME, REG_NO) VALUES ('Dr. A. Rahman', 'REG-001');
INSERT INTO DOCTOR_INFO (DR_NAME, REG_NO) VALUES ('Dr. B. Karim', 'REG-002');
INSERT INTO DOCTOR_INFO (DR_NAME, REG_NO) VALUES ('Dr. C. Chowdhury', 'REG-003');
COMMIT;

-- 1. Patient Info Table
CREATE TABLE PATIENT_INFO (
  PATIENT_ID VARCHAR2(50) NOT NULL, -- Changed to VARCHAR2
  FRONTEND_UUID VARCHAR2(64) NOT NULL UNIQUE, -- UUID from frontend for idempotency
  PATIENT_NAME VARCHAR2(255),
  GENDER VARCHAR2(20),
  DOB DATE,
  AGE VARCHAR2(20),
  CONTACT_NO VARCHAR2(50),
  ADDRESS VARCHAR2(500),
  DOCTOR_NAME VARCHAR2(200),
  -- REF_ID Removed
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PATIENT_ID)
);

CREATE SEQUENCE SEQ_PATIENT_ID START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PATIENT_ID
BEFORE INSERT ON PATIENT_INFO
FOR EACH ROW
BEGIN
  IF :NEW.PATIENT_ID IS NULL THEN
     :NEW.PATIENT_ID := 'p-' || SEQ_PATIENT_ID.NEXTVAL;
  END IF;
END;
/

-- 2. Patient Doc Info Table
-- Images linked to Patient
CREATE TABLE PATIENT_DOC_INFO (
  FILE_ID VARCHAR2(50) NOT NULL,
  PATIENT_ID VARCHAR2(50) NOT NULL, 
  SEQUENCE_NO NUMBER DEFAULT 0,
  PHOTO_MIME_TYPE VARCHAR2(100),
  patient_doc BLOB,
  PRIMARY KEY (FILE_ID),
  CONSTRAINT fk_patient_info FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT_INFO(PATIENT_ID) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FILE_ID START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER TRG_FILE_ID
BEFORE INSERT ON PATIENT_DOC_INFO
FOR EACH ROW
BEGIN
  IF :NEW.FILE_ID IS NULL THEN
    :NEW.FILE_ID := 'p-' || SEQ_FILE_ID.NEXTVAL;
  END IF;
END;
/

-- Comments
COMMENT ON TABLE PATIENT_INFO IS 'Stores metadata for digitized patient documents';
COMMENT ON COLUMN PATIENT_INFO.FRONTEND_UUID IS 'Unique ID from frontend to prevent duplicate uploads';
COMMENT ON TABLE PATIENT_DOC_INFO IS 'Stores the actual image data (BLOB) linked to the patient record';
